controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: forward_command_controller/ForwardCommandController

position_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - proximal_yaw_joint
      - proximal_pitch_joint
      - mid_yaw_joint
      - mid_pitch_joint
      - distal_yaw_joint
      - distal_roll_joint
    interface_name: position